### PR TITLE
Not Complete - Fix #565 - Models soft delete and restore, several icons and and Category lang

### LINKED ISSUE #565: Deleted assets list throw an error
When you goes to the url  /hardware?Deleted=true. If the related "models" associated to  the deleted "assets" the application throw an error. It could be fixed allowing to the models to have soft deleted too.

### PR DESCRIPTION
**Pull request by madd15**
Hoping this is on the right track, please let me know if any changes are required before merging.

### CODE REVIEW

**Comment by madd15** [comment]
sorry about the icons and lang being in the pr

**Comment by snipe** [comment]
5334_c663

**Comment by snipe** [comment]
Oh wow, that gave me 21 merge conflicts with my local dev :(

**Comment by madd15** [comment]
Didn't think i broke it that badly :(

**Comment by snipe** [comment]
No, you didn't. I had some changes I hadn't pushed up yet, so just a bunch of merge conflicts.

**Comment by madd15** [comment]
Ok cool, and that gif is kinda creepy

**Comment by snipe** [comment]
Hah - it's from an episode of The IT Crowd (which if you haven't watched that show, I'm not sure you're allowed to use my software anymore) called "The Haunting of Bill Crouse". It's hilarious and it's on Netflix. :)

**Pull request merged**
