### PR TITLE
Fix categories view columns matching

### LINKED ISSUE #12153: [BUG]: Categories table has mismatched columns
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Categories table has mismatched columns
image

### Reproduction steps

1. Go to Settings->Categories

### Expected behavior

Fix matching of columns

### Snipe-IT Version

6.0.13

### Operating System

Windows

### Web Server

IIS

### PHP Version

8.0

### PR DESCRIPTION
**Pull request by Robert-Azelis**
# Description
Fix categories view columns matching

Fixes #12153

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by snipe** [comment]
I'm not sure what this does, exactly. It's just an indentation change as far as I can see.

**Comment by snipe** [comment]
Weird, I must have had a stale view - I see the changes now

**Comment by snipe** [comment]
Thanks for this - can you retarget this to `develop`, per the develop documentation? Thanks!

**Comment by snipe** [comment]
Ugh, looks like you were using an older version of the branch or you branched directly off of master instead of develop before creating the feature branch - can you cherry pick out your changes? I shouldn't be seeing my commits in this PR.

**Comment by Robert-Azelis** [comment]
> Thanks - Hrm, looks like you were using an older version of the branch or you branched directly off of master instead of develop before creating the feature branch - can you cherry pick out your changes? I shouldn't be seeing my commits in this PR.

ok, recreated under develope branch [#12164](https://github.com/snipe/snipe-it/pull/12164#issue-1462176724)

**Comment by Robert-Azelis** [comment]
new one created https://github.com/snipe/snipe-it/pull/12164#issue-1462176724

**Pull request closed without merging**
