### PR TITLE
[Improvement] Manage EOL date by setup eol_explicit status

### PR DESCRIPTION
**Pull request by Robert-Azelis**
# Description

This improvement allow setup EOL date manually by user on damand by set eol_explicit checkbox.

**BEFORE:**
image

**AFTER:**
If checkbox is not checked then EOL date is hiden and calculation of date is on the base Model EOL rate
image

If checkbox is checked then EOL date is showed and user can input EOL Date manually.
Status of checkbox is saved as eol_explicit value
image

In this way is much easier to manage EOL date and explicit marker status instead of build complex rules  :)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

**Test Configuration**:
* PHP version: 8.1
* MySQL version 10.6.5-MariaDB
* Webserver version IIS
* Web browser: MS Edge, Chrome

# Checklist:

- [x] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [x] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by spencerrlongg — CHANGES_REQUESTED** [review]
Thanks for the PR! I think I see the advantage to this now. 

Could we add some text to the checkbox explaining what it is? I think it'd be a little confusing as is. It could just say "Explicit" or something. 

The one concern I have is if you check the box on an existing asset that has EOL months set on the model, the date box defaults to the calculated date (which makes sense) and then you can save an asset with `eol_explicit` set to `true`, even though it's the same as the calculated date. This could get a little confusing and defeat some of the purpose of the feature. 

Could we do a `diffInMonths()` check to make sure that it's _actually_ different before saving? 

Thanks again!

**Comment by Robert-Azelis** [comment]
> Thanks for the PR! I think I see the advantage to this now.
> 
> Could we add some text to the checkbox explaining what it is? I think it'd be a little confusing as is. It could just say "Explicit" or something.
> 
> The one concern I have is if you check the box on an existing asset that has EOL months set on the model, the date box defaults to the calculated date (which makes sense) and then you can save an asset with `eol_explicit` set to `true`, even though it's the same as the calculated date. This could get a little confusing and defeat some of the purpose of the feature.
> 
> Could we do a `diffInMonths()` check to make sure that it's _actually_ different before saving?
> 
> Thanks again!

**Comment by spencerrlongg** [comment]
Yeah, I think that's more or less what I mean for the text. 

We could still check if `purchase_date` is set and only do `diffInMonths()` if it has been, this way it's a little more obvious to the user when they select the option that the date is possibly still the same as the calculated date. 

Not a hill I'm ready to die on though - I do see your point about being able to set it explicit to not change the `eol_date` so that you can change the model eol without updating specific assets.

**Comment by Robert-Azelis** [comment]
I'm sorry, by mistake updated my branch by master, not sure how to revert changes, so re-created this PR under new #13846

**Pull request closed without merging**
