### PR TITLE
Allow multiple upload fields and add logo option to labels

### PR DESCRIPTION
**Pull request by smb**
Changed handling by id to look for a "uploadFile" css class.

Needs npm run dev/prod call for final deployment to master (but i think it's also needed for other changes in dev)

### CODE REVIEW

**Comment by snipe** [comment]
Hi - thanks for this! What problem does this solve?

**Comment by smb** [comment]
Allow preview + size check for multiple "logo" files in branding settings (currently only site logo does this):

image

also the next step (already working on this) is to move this code to a template/partial and add another one ("label logo") to be printed on asset labels.

**Comment by smb** [comment]
should i create another PR with the "logo on label" coding or just commit here and rename the PR? (since the new one would be build on commits of this one it would make sense to merge them into one PR)

**Comment by snipe** [comment]
You can just add to this one, and let me know when it’s ready - thanks!!

**Comment by smb** [comment]
Feel free to test!

image

Custom CSS added: (to demo new css options in label printing)

```
  .label-model::before {
    content: none;
  }
  .label-company::before {
    content: none;
  }
  .label-asset_tag::before {
    content: none;
  }
  .label-serial::before {
    content: "Serial: ";
  }
  .label-name::before {
    content: none;
  }  
  label-qr_text {
    font-size: 0.2in;
 }
```

Result:

image

**Pull request merged**
