### PR TITLE
Create a checkbox under match import possibility of variable

### PR DESCRIPTION
**Pull request by Thoronier**
HI,
 I have change the code in some files to add a checkbox. The checkbox is to determine whether the user has a lokaladmin on the asset, with appropriate extensions in the presentation.

1. **Create a new database field "localadmin"**
grafik

2. **Create an file to integrate the file in the view: localadmin.blade.php**
grafik

3. **Integrate the localdamin filte in the view (resources/views/hardware/edit.blade.php)**
grafik

4. **Extension of the import by local admin (dist/all.js)**
grafik

5. **Add in (app/Importer/Importer.php)**
grafik

6. **Add in (app/Importer/ItemImporter.php)**
function handle($row):
grafik

7. **Add the localadmin in (app/Models/Asset.php)**
grafik

grafik

8. **Add the localadmin in the AssetController:**
- (app/Http/Controllers/AssetController.php)
Function Store:
grafik

Function update:
grafik

- (app/Http/Controllers/Api/AssetController.php)
Function Store:
grafik

Function update:
grafik

9. **Add the localadmin in (app/Presenters/AssetPresenter.php)**
function dataTableLayout():
grafik

10. **Add/Create methods in (../resources/views/partials/bootstrap-table.blade.php)**
grafik

- add in function genericCheckinCheckoutFormatter(destination):
grafik

grafik

11. **Add/Change methods in (app/Http/Transformers/AssetTransformer.php**
function transformAsset:
grafik

### CODE REVIEW

**Comment by snipe** [comment]
Hi there - thanks for this! I'm still not 100% clear what this PR is meant to do.

> The checkbox is to determine whether the user has a lokaladmin on the asset, with appropriate extensions in the presentation.

I'm not sure what that means. Can you clarify?

Additionally, this is showing 497 files changes. I don't think that's quite right. Did you create this on your own fork and then apply the PR from there?

**Comment by DanielRuf** [comment]
>  into develop from master

Sounds not correct. Did you pick the right branch?

**Comment by snipe** [comment]
> Sounds not correct. Did you pick the right branch?

My guess here is that they didn't fork the repo and make a feature branch, but instead cloned the repo and are trying to apply changes directly to this repo.

**Comment by DanielRuf** [comment]
At least I see no commit from the user with the title from the PR in the list of commits of this PR. I think we can close this one.

I do not know but was the default branch `develop` sometime in the past?

**Comment by snipe** [comment]
> I do not know but was the default branch develop sometime in the past?

Default branch is always develop, but we still ask that people fork the repo and[ create a feature branch](https://snipe-it.readme.io/docs/contributing-overview#section-developing-on-snipe-it) (based off of develop).

**Comment by DanielRuf** [comment]
At least I see `master` as default in the dropdown =)
https://github.com/snipe/snipe-it

**Pull request closed without merging**
