### PR TITLE
Enhance further install without dummy data

### PR DESCRIPTION
**Pull request by roncsak**
Use --force to prevent user unnecessary user interactions.
Seed StatusLabels even when dummy datas chose to not be seeded because
snipe-it heavily builds on those table.
Seed Categories, because it is very common and goot to have, also.

### CODE REVIEW

**Comment by roncsak** [comment]
I was thinking using --force attribute is a good idea to decrease installation time a bit.
I'm kindly willing to get rid of it, if you think it is harmful in some way.

**Comment by snipe** [comment]
I don't have a problem with it. The status labels we populate happen in the migrations anyway, so I see no harm.

**Comment by snipe** [comment]
(They probably shouldn't happen in the migration, but they do right now, so...)

**Comment by snipe** [comment]
Was this a crazy-old fork or something?

**Comment by roncsak** [comment]
I'm relatively new on working with pull-request and upstream and origin and all...
I had some learning process while creating this pull request :smile:

**Comment by snipe** [comment]
tumblr_niqj53bbvb1smcbm7o1_500

Heh - no worries.

**Pull request merged**
