### PR TITLE
Feature/857 asset repair upgrade tracking

### PR DESCRIPTION
**Pull request by vsposato**
Implements #857 - Attaching this to the 2.0 branch as requested. This implements all the changes that were requested, in addition to the actual feature.

### CODE REVIEW

**Comment by snipe** [comment]
This looks good, I'll take a look at it this weekend - thanks! Btw, you don't need to handle the extra language files, just English. The platform we use, CrowdIn generates all of the necessary files for the other languages with English in their strings until the community translates them.

**Comment by snipe** [comment]
Did you pull the latest from 2.0 before submitting this PR? I'm seeing a lot of merge conflicts.

**Comment by vsposato** [comment]
I misunderstood what you originally said with regards to my pull request. In the future, I will make sure that I start from 2.0 and merge it into my branch prior to submitting the pull request.

**Comment by snipe** [comment]
Thanks - sorry this has been such an ordeal. We're reverting this merge right now, since it blew out lots of stuff, so hang on before starting at 2.0. I'll update here when the revert is complete and we've tested that the branch is stable again.

**Comment by snipe** [comment]
bad-hula

**Comment by snipe** [comment]
@vsposato should be all clear to pull from 2.0 now. 
happy-dance

**Comment by uberbrady** [comment]
I *think* - for these changes to get 'picked back up' - they're going to have to come across as new commits - trying to re-merge these will probably act weird and bizarre.

I think you can try to cherry-pick the commits into a new branch, based off of the current 2.0, and resubmit the PR? I think @snipe would prefer the commits to not be squashed, but be 'granular' - so I don't know if cherry-picking will turn them into new commit ID's or not.

You can chime in here or on Gitter and we will try and take another stab at getting this integrated into 2.0!

**Comment by vsposato** [comment]
Love the images! However, did you revert the changes completely? Should I go ahead and merge 2.0 into my local branch, and then pull request again.

**Comment by uberbrady** [comment]
I *think* it was a full revert.

**Comment by vsposato** [comment]
Ok, so I will pull my branch back down and merge 2.0 in, and fix the merge conflicts and validate functionality before I pull request again.

Does that work for everyone?

**Comment by uberbrady** [comment]
Basically, yeah, I think that should work. But I think the only 'gotchya' is that I think those commits are going to have to come back through with new ID's. If you know how to do that, that's great. If not - I will try and look up how to do that to give you some pointers.

But - step one, certainly, merge in 2.0 and get everything up and running again.

**Comment by snipe** [comment]
Yes, and thank you again for your patience. You've caught us right between versions, so it's a little messier than usual. We'll work towards communicating better in the future to avoid you having to do all this extra work. 

toomanyballs

**Comment by uberbrady** [comment]
```git rebase``` seems to be the magical way to get your commits to show up as new commits, which is (I think) what we want.

**Pull request merged**
