### PR TITLE
(develop - hotfix) Fix imports for 2FA Login

### PR DESCRIPTION
**Pull request by Mezzle**
Allows login via 2FA for those using it

### CODE REVIEW

**Comment by snipe** [comment]
I'm not 100% clear on what this fix does. The Google2FA process is handled in the auth controller, so there shouldn't be a need to apply it here... If you're not auth'ed properly according to the rules in your settings, you can't access the import anyway.

**Comment by Mezzle** [comment]
This fix basically adds in the import for `Google2FA` (and removes some unused imports).

See https://github.com/snipe/snipe-it/blob/d940e2e9da730cd756ab44d32f66480224488c11/app/Http/Controllers/Auth/LoginController.php#L217 - the `Google2FA` is being used here in the `LoginController` and without it - you get a lovely error

image

**Comment by snipe** [comment]
I'm kinda not clear why our local tests didn't catch that....

I was confused by the title of the PR, since it mentioned imports.

**Comment by Mezzle** [comment]
Do you have 2FA enabled for local tests?  

Would you be interested in me throwing something like https://github.com/phpstan/phpstan at your repo to do a bunch of checking?

How about setting up something like https://github.com/phpro/grumphp ? I've a bunch of default settings available over https://github.com/sane-defaults for quick setup

**Comment by snipe** [comment]
> Do you have 2FA enabled for local tests?

Of course :) would be pretty hard to test 2FA if I didn't.

We already use a lot of the code quality tools with Codacy.

**Pull request merged**
