### PR TITLE
Fixed footer sizing issue

### PR DESCRIPTION
**Pull request by Godmartinz**
# Description
Rethought the fix for the footer. I moved everything to one div. 
Just one line of custom footer:
image

Extra Long custom footer with line breaks:
image

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* PHP version:
* MySQL version
* Webserver version
* OS version

# Checklist:

- [ ] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [ ] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by snipe** [comment]
This changes the current way the footer displays though. Maybe that's a good thing, maybe it's not. 

Current: 
Screenshot 2023-04-24 at 12 18 26 PM

The positions have changed here, where normally the "Snipe-IT is open source software" is on the left, version on the right, with the custom text ahead of it.

**Comment by Godmartinz** [comment]
Swapped it back 🙂 
image
Footer text will appear on the line below as well.

**Comment by Godmartinz** [comment]
@snipe is there anything that needs to be rethought with this?

**Comment by Godmartinz** [comment]
Is this solution acceptable for now?

**Pull request merged**
