### PR TITLE
Another importer fix.

### PR DESCRIPTION
**Pull request by dmeltzer**
Fix condition where matching user fails when providing a username but no full name.  Also shortcircuit username matching if a username exists.

Should provide a test for this... but I have to run at the moment. Remind me later :)

### CODE REVIEW

**Comment by dmeltzer** [comment]
The second commit above makes some changes to how we handle logic around providing a number as the users name.  Previously if a number was provided, we assumed it was a user's id from the database, and looked up that id.  If a user matching that ID existed, we'd return that user, otherwise we'd jump straight to creating a user with a full name of that id and whatever username /email was provided.  This runs that user's full name through the logic that guesses usernames/emails/first+last names based on the full name.

Alternatively we may want to think about removing this "feature".  It seems much more straightforward to just support username matching or add a "user id" field.  Relying on the user's name as a number to be an id feels like it could have surprising unexpected consequences given how not documented it is.

**Comment by fletch8527** [comment]
Applied updated Importer.php. Confirmed that when a username column in the csv file was mapped to the 'Username' field for the import that the asset was correctly checked out to that user. My users were synced from LDAP/AD prior to the asset import and I used the samaccountname from AD as the username for the import. I opened an issue (#5363 ) regarding this and Import History. Appears that I can now import assets and have them assigned. Import History still does not work at this time.

**Comment by yokhoe** [comment]
Hello, is this fix implemented in 4.3.0? I too have users who are imported from LDAP/AD and this is the only format the importer is capable of processing.  The problem is even if I switch the Header Field 'username' to Import Field 'checked out to', it doesn't show the asset as being checked out.  I tried selecting Import Field 'Full Name' and it is stuck on processing.  

image

BTW, I think the notes on the docs between the Import guide page vs the Importer issues guide page in regards to this subject can be written around the same language.  At this moment, I think the difference brings out some confusion.

**Comment by fletch8527** [comment]
@yokhoe you have to map your username header to the username field (not 'checked out to' or 'full name') it worked for me

**Comment by yokhoe** [comment]
@fletch8527 not for me, I did that as well previously, keeping the Username header from the CSV and map it to the Username field. It imports, but it doesn't list the assets as being checked out to that user

**Comment by TrevorCostello** [comment]
Having the same issue, the import history gives success but doesn't actually check out the items to the user. Also tried the Name field instead of username. I'm resorting to manually bulk checkout for hundreds of items per user. Wish this would get resolved. Or at least allow comma separated asset #'s rather than searching for each one and having to select it in the bulk checkout screen.

**Pull request merged**
