### PR TITLE
Added Redis support.

### PR DESCRIPTION
**Pull request by MelonSmasher**
added `predis/predis` dependency to composer.json to support redis based cache/queue/session/broadcast

### CODE REVIEW

**Comment by snipe** [comment]
Per the Contributing docs, please make PRs to the develop branch. 

Additionally, is there a particular reason you want redis support? This isn't typically used as a high-performance/concurrency app, so local session handling is usually sufficient. 

Thanks!

**Comment by MelonSmasher** [comment]
Apologies for sending this to the wrong branch. Generally I like to have the flexibility of having redis available for Laravel projects in the event that they need to be load balanced or HA. I do plan on setting up Snipe in two datacenters behind a reverse proxy, and it would be great to have them share sessions.

**Comment by snipe** [comment]
Sure - you should just be able to retarget this one though, no need to close and re-open

**Comment by MelonSmasher** [comment]
Good call. Alls set.

**Pull request merged**
