### PR TITLE
Barcode Reader Support

### PR DESCRIPTION
**Pull request by MimoGraphix**
Allows to scan barcode on the Label, put it into Search field  and redirect to specific Asset.
Barcode reader needs to be set with specific  Prefix(Default: ~) and Suffix(Default: Enter), settings can be changed in config/barcode.php

### CODE REVIEW

**Comment by snipe** [comment]
Hi there - thanks for this. I'm unclear what this PR really does though. The top search bar already does this, that's why it takes the focus as long as no other form on the page has been activated. (We've tested this pretty extensively with USB barcode scanners.)

Additionally, it looks like this PR needs a recent pull or a rebase, as it's got tons of my commits in it.

**Comment by MimoGraphix** [comment]
Hi, Barcode on label has written in "NAME_OF_ASSET", but many companies like ours is already using Barcode readers for other applications, these barcode readers needs to have specific setup, because applications response differently when input came from keyboard and barcode reader.

For example when I read barcode with NAME_OF_ASSET my barcode reader give me ~NAME_OF_ASSET[Enter] when I put this in search bar in Snipe-it it returns nothing.

For this reason I made this change.

I am sorry I made mistake it should be snipe:develop branch not snipe:master.

**Comment by snipe** [comment]
I'll have to look at this closer. I'm not sure this is the best way to implement it. That search box is looking for an asset tag, not an asset name. We could set the prefix up as a column in the database tables, potentially, but it will still need an asset tag, not a name. I'm on the road at the moment, but will look into this more once I'm back in front of my laptop. Web apps respond the same way to a barcode reader as they do keyboard input.

Per the contributing docs, PRs should be done against the develop branch.

**Comment by MimoGraphix** [comment]
Yes I know it should be develop, just choose wrong branch it was by mistake. I changed branch to the correct one.

**Comment by snipe** [comment]
Additionally, you do not need to create the alt language file entries when you add new strings. More info here: https://snipe-it.readme.io/docs/contributing#section-localization-support

**Comment by snipe** [comment]
Can you resubmit this PR without the language file changes? It's hard to sort through the legitimate changes. Thanks!

**Pull request closed without merging**
