### PR TITLE
Add support for location-specific LDAP OUs.

### PR DESCRIPTION
**Pull request by richardhofman6**
First attempt at implementing location-specific LDAP OUs for user import.

As discussed in #3004.

### CODE REVIEW

**Comment by richardhofman6** [comment]
The error in the Travis build seems to be unrelated to my changes - possibly due to other stuff happening in the develop branch?

**Comment by snipe** [comment]
Awesome, thanks so much! I'll take a look at this tonight. I know a lot of people will be excited to have this functionality and it's just not something I've had time to do yet. I'd love to scoop it into v4.

Don't worry about Travis failing - that's probably  me, breakin' shit :)

**Comment by snipe** [comment]
Yeah, it's definitely me :) I'm gutting all of the routes and controllers to make way for the API. Messy business, but I also don't want to go too long without pushing lest I end up in merge hell.

**Comment by snipe** [comment]
Nice work! Thanks again!

**Comment by richardhofman6** [comment]
No worries - glad I could contribute, Snipe IT is an awesome tool. Looking forward to the API! :)

**Comment by snipe** [comment]
Me too! :D I've got a live API tool running now if you want to play with it, although it's still very early on. Lots of ugly legwork had to happen before we could start writing the actual API methods (upgrading to Laravel 5.3, breaking out the routes, etc): 

https://snipe-it.readme.io/v4.0/reference

(Click on the Try It button above the example responses.) Not all of the parameters work yet, but we're getting there.

**Pull request merged**
