### PR TITLE
Configuration Volume

### PR DESCRIPTION
**Pull request by astutecat**
Having the ability to optionally store config outside of the container is desirable - this means that when a new version of the container is released, the existing container can be removed and replaced without any configuration data being lost.

In particular, this means that a container like watchtower (https://github.com/CenturyLinkLabs/watchtower) can do this automatically when a new container is pushed (although running migrations automatically when the new container is launched may be required in that case)

Proposed is a volume bound to /opt/snipe-it/config which links to /var/www/html/app/config/production/ in the container.

This volume would then be used with the -v command line switch, e.g:

sudo docker run --restart=always -d -p 8080:80 --name="snipe-it" --link snipe-it-mysql:mysql -v /path/to/config/files:/opt/snipe-it/config --env-file=/home/snipe-it/docker.env snipe/snipe-it

### CODE REVIEW

**Comment by astutecat** [comment]
Although in hindsight, /opt probably isn't the right home for said directory - maybe a virtual /etc/ directory?

**Comment by snipe** [comment]
It might be worth noting that Snipe-IT v3 is coming out very soon, and it uses `.env` files instead of the (many) config files the current version of Snipe-IT uses. Not sure if that changes anything.

**Comment by astutecat** [comment]
That actually makes this pull request pretty redundant, provided that everything that needs to persist configuration-wise is held in that .env file between interations of container... I'll wait for 3 to come out then :)

**Comment by snipe** [comment]
Heh, yeah, unfortunately Laravel 4.2 (which is what Snipe-IT current) is running on doesn't natively support .env files. But v3 is very close, so hopefully you won't have to wait long. 

If you're interested in seeing what's coming, you can check out the post here:
https://github.com/snipe/snipe-it/issues/1800

(I really wish GH would let me pin issues. Sigh.)

**Pull request closed without merging**
