### PR TITLE
Fixing #5773: Refactoring the "clearing" of select2 lists

### PR DESCRIPTION
**Pull request by tilldeeke**
This PR refactores the "clearing" of select2 lists to the native clearing that the library offers.

select2 shows an "x" on a list with a selected value, allowing the field to be cleared:
krywa0dysf

This also works on multiple select now, so #5773 should be fixed by this:
b80as2pq0e

### CODE REVIEW

**Comment by romannazarenko** [comment]
Ok

15 июл. 2018 г. 15:26 пользователь "Till Deeke" <notifications@github.com>
написал:

This PR refactores the "clearing" of select2 lists to the native clearing
that the library offers.

select2 shows an "x" on a list with a selected value, allowing the field to
be cleared:
[image: krywa0dysf]
<https://user-images.githubusercontent.com/1795149/42733873-f7b220e8-8839-11e8-9137-b565e069ef57.gif>

This also works on multiple select now, so #5773
<https://github.com/snipe/snipe-it/issues/5773> should be fixed by this:
[image: b80as2pq0e]
<https://user-images.githubusercontent.com/1795149/42733877-1767921a-883a-11e8-9785-a92cd5fb8fcd.gif>
------------------------------
You can view, comment on, or merge this pull request online at:

  https://github.com/snipe/snipe-it/pull/5839
Commit Summary

   - adds select2 placeholders to select lists
   - Removes empty option from multiple select
   - Adds the option to clear select2 instances
   - Removes the „Clear selection“ option from select lists
   - Updates generated assets (css/js)

File Changes

   - *M* app/Http/Transformers/SelectlistTransformer.php
   <https://github.com/snipe/snipe-it/pull/5839/files#diff-0> (6)
   - *M* public/css/AdminLTE.css.map
   <https://github.com/snipe/snipe-it/pull/5839/files#diff-1> (2)
   - *M* public/css/app.css.map
   <https://github.com/snipe/snipe-it/pull/5839/files#diff-2> (2)
   - *M* public/css/overrides.css.map
   <https://github.com/snipe/snipe-it/pull/5839/files#diff-3> (2)
   - *M* public/js/build/all.js
   <https://github.com/snipe/snipe-it/pull/5839/files#diff-4> (12)
   - *M* public/js/build/vue.js
   <https://github.com/snipe/snipe-it/pull/5839/files#diff-5> (2)
   - *M* public/js/build/vue.js.map
   <https://github.com/snipe/snipe-it/pull/5839/files#diff-6> (2)
   - *M* public/js/dist/all.js
   <https://github.com/snipe/snipe-it/pull/5839/files#diff-7> (12)
   - *M* public/mix-manifest.json
   <https://github.com/snipe/snipe-it/pull/5839/files#diff-8> (14)
   - *M* resources/assets/js/snipeit.js
   <https://github.com/snipe/snipe-it/pull/5839/files#diff-9> (7)
   - *M* resources/views/partials/forms/edit/asset-select.blade.php
   <https://github.com/snipe/snipe-it/pull/5839/files#diff-10> (6)
   - *M* resources/views/partials/forms/edit/category-select.blade.php
   <https://github.com/snipe/snipe-it/pull/5839/files#diff-11> (2)
   - *M* resources/views/partials/forms/edit/company-select.blade.php
   <https://github.com/snipe/snipe-it/pull/5839/files#diff-12> (2)
   - *M* resources/views/partials/forms/edit/department-select.blade.php
   <https://github.com/snipe/snipe-it/pull/5839/files#diff-13> (2)
   - *M*
   resources/views/partials/forms/edit/location-profile-select.blade.php
   <https://github.com/snipe/snipe-it/pull/5839/files#diff-14> (2)
   - *M* resources/views/partials/forms/edit/location-select.blade.php
   <https://github.com/snipe/snipe-it/pull/5839/files#diff-15> (2)
   - *M* resources/views/partials/forms/edit/manufacturer-select.blade.php
   <https://github.com/snipe/snipe-it/pull/5839/files#diff-16> (2)
   - *M* resources/views/partials/forms/edit/model-select.blade.php
   <https://github.com/snipe/snipe-it/pull/5839/files#diff-17> (2)
   - *M* resources/views/partials/forms/edit/supplier-select.blade.php
   <https://github.com/snipe/snipe-it/pull/5839/files#diff-18> (2)
   - *M* resources/views/partials/forms/edit/user-select.blade.php
   <https://github.com/snipe/snipe-it/pull/5839/files#diff-19> (2)

Patch Links:

   - https://github.com/snipe/snipe-it/pull/5839.patch
   - https://github.com/snipe/snipe-it/pull/5839.diff

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/snipe/snipe-it/pull/5839>, or mute the thread

**Comment by dmeltzer** [comment]
Hi,

This looks great--thanks for the PR.

@snipe Just committed a few minutes to trying to figure out why there wasn't off-by-one errors with this given  that Helper::*List adds a blank entry to each array, and then discovered that we no longer use those methods it appears--maybe worth removing when this gets committed as well?

**Comment by dmeltzer** [comment]
Okay-- Looks like the following places still use the "old way" and do not allow for the quick clear.

- Categories/edit for the categoryTypeList() (coming from Helper.php)
- Models/edit, Licenses/edit for depreciationList() (Coming from Helper.php)
- statusTypeList() for AssetsController/StatuslabelsController

**Comment by snipe** [comment]
fallon-thank-you

**Pull request merged**
