### PR TITLE
Add manager to location

### PR DESCRIPTION
**Pull request by dmeltzer**
Infrastructure background for what we were talking about, plus some bug fixes to location view page.  

This adds a "manager" field to a location, and implements related logic.  If a user is managing a location they cannot be deleted until they are no longer a manager.  Add a list of locations a user manages to their view page (We may want to add this for users too at some point..)

### CODE REVIEW

**Comment by dmeltzer** [comment]
Rebased against current develop.  This should be good to go.  If nothing else, 04a2d55 would be good to cherry-pick, it fixes some issues on the locations view page.

**Comment by snipe** [comment]
Will you be able to resolve these conflicts, or should I try to tackle it?

**Comment by dmeltzer** [comment]
Let me try to rebase, it shouldn't be too bad.

**Comment by snipe** [comment]
Just pinging you on this one :)

**Comment by snipe** [comment]
Never mind, I handled it :)

**Pull request merged**
