### PR TITLE
Refactoring: A nicer and easier syntax for searching models

### LINKED ISSUE #5588: unable to search date for purchase date or invoice date. I tried to search but it doesn't appear the date that we need search on the search field.
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? 
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.
image

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/58767038-unable-to-search-date-for-purchase-date-or-invoice-date-i-tried-to-search-but-it-doesn-t-appear-the-date-that-we-need-search-on-the-search-field?utm_campaign=plugin&utm_content=tracker%2F505106&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F505106&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by tilldeeke**
This PR adds the ability to search any model by their "date" columns. 
You can now search for the completion date of asset maintanances, purchase dates of components, creation dates of assets, etc.

This should fix #5588.

### CODE REVIEW

**Comment by dmeltzer** [comment]
This might be a good candidate for a Helper::addDateQueries() method to make adjusting it in the future better.

**Comment by tilldeeke** [comment]
I totally agree, right now it's basically just copy pasted into every model, thats not very DRY.
I noticed that some of the `scopeTextSearch` methods are quite complex and hard to understand. I thought about refactoring the whole search "engine", but I did not have enough time to look at that just yet 😅

**Comment by tilldeeke** [comment]
I just noticed #4590, in which searching something using chinese characters cases problems.
This PR would reopen that issue, since mysql would fail to search a "TIMESTAMP" column with characters that are not in the english alphabet.

**Comment by tilldeeke** [comment]
With this refactoring it is now possible to define the searched attributes and relations of a model in a cleaner way. Using the `Searchable`-Trait, most Models can just declare the attributes and relations that should be searched:

```php
use Searchable;

/**
 * The attributes that should be included when searching the model.
 * 
 * @var array
 */
protected $searchableAttributes = ['name', 'model_number', 'purchase_date'];

/**
 * The relations and their attributes that should be included when searching the model.
 * 
 * @var array
 */
protected $searchableRelations = [
    'manufacturer' => ['name', 'support_email'],
    'supplier'     => ['name'],
];
```

The Trait handles searching in dates gracefully as well, avoiding issues like #4590.

More advanced queries can also be run in addition to the other attributes:
```php
/**
 * Run additional, advanced searches.
 * 
 * @param  Illuminate\Database\Eloquent\Builder $query
 * @param  string  $term The search term
 * @return Illuminate\Database\Eloquent\Builder
 */
public function advancedTextSearch(Builder $query, string $term) {
    $query = $query->orWhereRaw('CONCAT('.DB::getTablePrefix().'users.first_name," ",'.DB::getTablePrefix().'users.last_name) LIKE ?', ["%$term%", "%$term%"]);

    return $query;
}
```

**Comment by snipe** [comment]
tenant-tyvm

Really appreciate all of the work you've put in recently - it's a huge help!

**Comment by tilldeeke** [comment]
Thanks! It's a lot of fun to look at the issues and try to solve them in a way that fits the existing code and paradigms, while improving the code overall!

(And it's perfect to clear my head after studying for exams the whole day 😅)

**Pull request merged**
