### PR TITLE
FIXED RecryptFromMycrypt not working really

### PR DESCRIPTION
**Pull request by TonisOrmisson**
tried to upgrade from v3.6 with a base64 key and different rijndael-256 cipher and ran into a bunch of errors. Starting from using an object instead of proiperty name etc.

Anyway. this solution worked for me.

probably would need to detect somehow if the cipher has changed during upgrade and prompt/suggest to enter that in the .env somehow?

### CODE REVIEW

**Comment by snipe** [comment]
> probably would need to detect somehow if the cipher has changed during upgrade and prompt/suggest to enter that in the .env somehow?

Yeah, that's specifically why I didn't add the cipher detection in the recrypter. :-/

Can you re-target this to develop, per the contributing docs?

**Comment by snipe** [comment]
Additionally, I'm not certain exactly what "not working really" means. I tested this with multiple legacy ciphers without issue. Can you explain what specific problem you're trying to solve with this?

**Comment by TonisOrmisson** [comment]
sure :)

I had trouble with the custom fields. 
so this section:
https://github.com/snipe/snipe-it/pull/4244/files#diff-ac577a37cc77bcd2923c1f81315ba23dL117
does not seem to do anything other than just looping and doing nothing. Not a problem really but seems just unneccessary.

but here:
https://github.com/snipe/snipe-it/pull/4244/files#diff-ac577a37cc77bcd2923c1f81315ba23dL117
there was `$asset->{$encrypted_field}` while the `$encrypted_field` was an CustomField[] object, not something one could use for parameter and this I do not believe would work on any system ;) 

So there is multiple issues here actually (why I had trouble naming it)

Anyway i can not see how current code would work at all with custom ciphered fields or?

**Comment by TonisOrmisson** [comment]
I'll post this to develop

**Pull request closed without merging**
