### PR TITLE
Docker2 (DO NOT MERGE YET)

### LINKED ISSUE #437: Official Docker image?
I was wondering if you were looking to make an official Docker image / dockerfile for SnipeIT?

It would certainly make deployment and upgrades a lot easier.

### PR DESCRIPTION
**Pull request by uberbrady**
Initial Dockerfile created; some relatively common-sense (but still helpful, at least for me) instructions on how to use it in docker/README.md

I think email may not work yet, I still need to figure that out. But I can at least get this PR started.

Fixes #437

### CODE REVIEW

**Comment by uberbrady** [comment]
Email integration seems to work OK; I think this is ready to merge.

**Comment by sammcj** [comment]
ughhh apache2 :/

**Comment by snipe** [comment]
Thanks, @uberbrady! close-enough

@sammcj - pull requests are always welcome ;)

**Comment by snipe** [comment]
@sammcj Honestly, it shouldn't really matter what web server it's using. You're not going to need to be changing it much (ever).

**Comment by sammcj** [comment]
Compared to Nginx Apache is just old and heavy, it's configuration is a mess and mod-php is a dog compared to php-fpm - there's just no real reason to use it these days, especially inside lightweight containers.  

But hey, that aside, good work and it's great to see a working Dockerfile for the project!

**Comment by snipe** [comment]
@sammcj - Apache2 is still used in production on millions of web servers. It's configuration is actually pretty simple, and PHP being a dog or not doesn't really matter on an internal application like this that isn't dealing with millions of users. I run Apache2 on the hosted version for our clients and have zero issues.

But again, pull requests are always welcome ;)

**Comment by cleathley** [comment]
Hi Guys

Can I suggest the following changes.  Including php5-gd so the QR functionality of snipe-it works ;)

RUN php5enmod gd

And the following which allows for existing installations to be updated with the correct key and turning off the development tool bar (these can be commented out)

# inject our proper key
#RUN sed -i s%Change_this_key_or_snipe_will_get_ya%<PUT YOUR APP KEY HERE>% /var/www/html/app/config/production/app.php

# turn off the toolbar
#RUN sed -i 's%\x27debug\x27 => true%\x27debug\x27 => false%' /var/www/html/app/config/production/app.php

Really like snipe-it and having a docker install is great.

**Comment by snipe** [comment]
Hi @cleathley - thanks so much for your suggestions. They seem really reasonable. We'll get @uberbrady on those fixes. I'm sure he'll be really stoked to help, since it means his hard work means people are using it :)

**Comment by uberbrady** [comment]
The  gd thing - absolutely, of course. Give me a pull request and I'll merge it (and you'll get Open Source Brownie Points!), if not I'll do it myself.

The app key - you think an environment variable might work well for this?

**Comment by cleathley** [comment]
An environment variable would be better as it's the docker way. just need to test if it works on a clean install

**Pull request merged**
