### PR TITLE
Fixed tooltips and iCheck

### PR DESCRIPTION
**Pull request by jwhulette**
Reference: https://github.com/snipe/snipe-it/pull/6285#issuecomment-427235280

### CODE REVIEW

**Comment by snipe** [comment]
Thanks! Can you resolve the conflicts?

**Comment by snipe** [comment]
(Also bear in mind I made some changes to the JS last night, adding in jquery-form-validator)

**Comment by snipe** [comment]
Thanks! This might be a bizarre question, but did they change color and lose their tail? This is what they look like now:

screen shot 2018-10-05 at 7 55 21 am

And this is the way they're supposed to look in Bootstrap 3:

screen shot 2018-10-05 at 7 55 32 am

**Comment by jwhulette** [comment]
There seems to be a conflict with Jquery-UI and bootstrap both using a tooltip function. I think it's using the jQuery-UI tooltip. If you look at the master branch, I think it is only using regular html tooltips.
I'll look into it to see what I can do, now that I have time as I just got laid off.

**Comment by snipe** [comment]
> There seems to be a conflict with Jquery-UI and bootstrap both using a tooltip function. 

I don't think we've changed tooltips in quite some time tho. Why would this just show up now?

> now that I have time as I just got laid off.

OH NO! :( Do you have a CV I can pass around for you? (I can at least tweet it?) That really sucks, man. I'm so sorry.

**Comment by snipe** [comment]
> Thanks for the offer. I have some feelers out locally, but I'll hit you up if they fall through.

Please don't hesitate. 

> The current version of v4 is not using bootstrap tooltips that I can see it

We initialize it here:

https://github.com/snipe/snipe-it/blob/708b1a962ce1efd25ea5018219c6e9c8887e9cc2/resources/views/layouts/default.blade.php#L814

https://getbootstrap.com/docs/3.3/javascript/#tooltips-usage

**Pull request merged**
