### PR TITLE
Select2 Changes

### PR DESCRIPTION
**Pull request by takuy**
These changes will allow submissions during the AJAX process in Select2s. This allows for barcode scanners, magstrip and NFC scanners that enter a carriage return. If you press enter while typing something and AJAX is not complete, it'll force an AJAX and use the first response. Disregards selects based on mouse events.

### CODE REVIEW

**Comment by takuy** [comment]
This attempts to fix the behavior reported in 5857

**Comment by snipe** [comment]
Did you actually try to compile these assets? I get 

```
> @ production /Users/snipe/Sites/snipe-it/snipe-it
> cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

 95% emitting DONE  Compiled successfully in 39929ms                                                                                                                                              12:09:12 AM

Whoops! We had trouble minifying "public/js/dist/all.js". Perhaps you need to use mix.babel() instead?

/Users/snipe/Sites/snipe-it/snipe-it/node_modules/laravel-mix/src/webpackPlugins/CustomTasksPlugin.js:64
                    throw e;
                    ^
SyntaxError: Unexpected token: operator (>)
    at JS_Parse_Error.get (eval at <anonymous> (/Users/snipe/Sites/snipe-it/snipe-it/node_modules/uglify-js/tools/node.js:1:0), <anonymous>:86:23)

npm ERR! Darwin 17.7.0
npm ERR! argv "/Users/snipe/.nvm/versions/node/v6.11.3/bin/node" "/Users/snipe/.nvm/versions/node/v6.11.3/bin/npm" "run" "production"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @ production: `cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js `
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ production script 'cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js '.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/snipe/Sites/snipe-it/snipe-it/npm-debug.log
```

**Comment by snipe** [comment]
This is an issue that comes up sometimes with compiling production assets. Uglify cannot grok some ES6 stuff, so you have to use older style javascript. We've fixed it and the assets compile correctly now. :)

Thanks for the PR!

**Comment by takuy** [comment]
Ah yeah, I tried to compile the assets and ran into that error. Figured it would be brought up during the review. No ES6, got it! Thanks!

**Pull request merged**
