### PR TITLE
added installer support for Fedora

### PR DESCRIPTION
**Pull request by sorvani**
Successfully installs on Fedora 25 and 26 in my own testing.

### CODE REVIEW

**Comment by snipe** [comment]
Hi there - thanks for this! Can you please re-target this PR to point to the `develop` branch, per [our Contributing documentation](https://snipe-it.readme.io/docs/contributing-overview)? 

You don't need to close and re-open. After you create a pull request, you can modify the base branch so that the changes in the pull request are compared against a different branch. By changing the base branch of your original pull request rather than opening a new one with the correct base branch, you’ll be able to keep valuable work and discussion.

mhuxq

Thanks!

**Comment by sorvani** [comment]
Moved.
I was working from master not develop. so if there are conflicts I'll redo the entire thing later.

**Comment by sorvani** [comment]
Asked a few others to test it and they also had no issues.
https://mangolassi.it/topic/15416/testing-snipeit-on-fedora

**Comment by snipe** [comment]
Can you rebase this and re-push? I'm seeing bunch of my own commits a part of the commits list.

**Comment by sorvani** [comment]
It will be a while. I am at a conference today and taking the kids for a weekend trip tomorrow. I will try and get to it over the weekend but no promises

**Pull request closed without merging**
