### PR TITLE
[FIX and improvements] EOL rate and EOL date

### PR DESCRIPTION
**Pull request by Robert-Azelis**
# Description

Some improvements :
- display EOL rate for assets (real rate as diff between pruchase date and eol date),
- display market in asset details if EOL date is expired,
- display EOL rate as months
- upated name of column from 'EOL' to 'EOL rate'

Some fixes:
- during update check model EOL rate if is >0 or =0, set correct status explicit marker,
- during edit asset read real eol date from database instead calculate on base model eol,
- keep consistance during update model EOL rate 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

**Test Configuration**:
* PHP version: 8.1
* MySQL version 10.6.5-MariaDB
* Webserver version IIS
* Web browser: MS Edge, Chrome

# Checklist:

- [x] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [x] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by snipe** [comment]
Thanks for this - can I have some screenshots of the before and after? It's hard for me to tell what you're going for here.

**Comment by Robert-Azelis** [comment]
Change of display EOL rate in Assets
Befor:
image

After:
image

**Comment by Robert-Azelis** [comment]
Change of display EOL rate (calculate real rate on the base diff between purchase date and eol date) and added expiration marker for EOL date (like for warranty expires)
Before:
image

After:
image

**Comment by Robert-Azelis** [comment]
beside visual changes, little improvement some logic rule of calculation eol date and set explicit marker.

**Comment by snipe** [comment]
@spencerrlongg can you take a look at this please. I know you were working on EOL stuff recently.

**Pull request merged**
