### PR TITLE
Deb/Ubu progress bar

### PR DESCRIPTION
**Pull request by mtucker6784**
Added progress bar, tested on Debian/Ubuntu. Also added php-xml as an Ubu 16 package install.

### CODE REVIEW

**Comment by snipe** [comment]
Getting a merge conflict. Can you resolve?

**Comment by mtucker6784** [comment]
Still learning git after all this time.  Good griefsauce. >.>

**Comment by mtucker6784** [comment]
holy shit, I give. Let me start this over. Haha

**Comment by snipe** [comment]
Hah - yeah, git is awesome and miserable at the same time. Just make sure you have afresh checkout of the develop branch, and you should be okay.

http://ohshitgit.com

**Pull request closed without merging**
