### PR TITLE
On install, force debug on in the middle ware until setup is complete

### PR DESCRIPTION
**Pull request by dmeltzer**
This should make debugging easier in general I hope.  Tested with APP_DEBUG=false and true, before and after setup.

### CODE REVIEW

**Comment by snipe** [comment]
If permissions are the issue, I don't think the middleware will even load tho?

**Comment by snipe** [comment]
Did these changes somehow get stuck together? I don't think we need/want the middleware change, since it won't help with log permissions, but the importer stuff we probably do.

**Comment by snipe** [comment]
I just manually patched this with the importer changes - closing this for now.

**Comment by dmeltzer** [comment]
yeah, we can ignore this one.  I committed to the same branch by accident locally and github got excited.

**Pull request closed without merging**
