### PR TITLE
docker: Fix upgrades

### PR DESCRIPTION
**Pull request by lubo**
Until now, the Docker image was not performing actions that are necessary for an upgrade completion. That is considered an anti-pattern.

See https://snipe-it.readme.io/docs/upgrading for more information.

### CODE REVIEW

**Comment by uberbrady** [comment]
I mean, I would assume you wouldn't want to upgrade a Snipe-IT container; you'd instead just want to launch a new one with the new version, and discard the old one.

But I suppose it's not up to us to dictate how people use Docker. Some people might want to work this way and we shouldn't tell them not to.

I wish there were a way to do the config:clear and config:cache *only* if the upgrade has happened.

Or maybe the instructions ought to be - if you want to in-place upgrade your container, run a few `docker exec` lines and do these steps? Not sure.

Will ponder.

**Comment by lubo** [comment]
You can do that by providing a custom command. For example, `$ docker run snipe/snipe-it php artisan migrate --force` will only run the migrations in a new container. It's just that by default, there should be no manual intervention required.

When it comes to `config:clear` and `config:cache`, do you have any suggestions? Perhaps the easiest way of detecting an upgrade would be if the old version string was persisted somewhere and we could compare it with the current version string.

What do you mean by _“in-place upgrade your container”_? The containers should be immutable. If you want to upgrade, you should spawn a new container from different image.

**Comment by lubo** [comment]
@uberbrady Ping.

**Comment by lubo** [comment]
@uberbrady I've modified https://github.com/snipe/snipe-it/pull/6680#issuecomment-460540281 after realizing we didn't understand each other. Please, take a look again.

**Comment by snipe** [comment]
Thanks, dudes!

**Comment by samatkiss** [comment]
Hi!

Sorry but i cant understand now that the new container upgrade the database automatically or not? 
Thanks 
T.

**Comment by lubo** [comment]
@samatkiss Containers will attempt to run database migrations on every startup. I believe these changes will be included in version 5.

**Comment by samatkiss** [comment]
Hi!
Thanks! I see now.

**Pull request merged**
