### PR TITLE
load custom css also on login page

### PR DESCRIPTION
**Pull request by thakilla**
load custom css also on login page

### CODE REVIEW

**Comment by snipe** [comment]
Hi there - thanks for this! Can you please re-target this PR to point to the `develop` branch, per [our Contributing documentation](https://snipe-it.readme.io/docs/contributing-overview)? 

You don't need to close and re-open. After you create a pull request, you can modify the base branch so that the changes in the pull request are compared against a different branch. By changing the base branch of your original pull request rather than opening a new one with the correct base branch, you’ll be able to keep valuable work and discussion.

mhuxq

Thanks!

**Comment by thakilla** [comment]
Oh, sorry for that. I changed it to develop.

**Comment by snipe** [comment]
Can you rebase this as well? It's showing a bunch of my commits. 

screen shot 2017-10-19 at 4 38 06 am

**Comment by thakilla** [comment]
rebased also here...

**Comment by snipe** [comment]
ty-for-that

**Pull request merged**
