### PR TITLE
Fixed feedback on #2349

### PR DESCRIPTION
**Pull request by zjean**
Hi,
I gave it another try by fixing the feedback you gave me ;-)

### CODE REVIEW

**Comment by snipe** [comment]
Nice work on this. I'm probably going to move the bulk checkout button out of the top header, simply because from an information architecture perspective, you can only bulk checkout assets, so it makes more sense to have it within the Assets sidenav (and also adding that there makes bad things happen on mobile).

This isn't the way I'd have approached this - I'd have used the bulk edit/delete checkbox+dropdown on the assets listing page, but this certainly works too.

**Comment by snipe** [comment]
marsden-like-this

**Comment by zjean** [comment]
Thanks!
The way I chose to do it like this, instead of using the check boxes on the asset listing page, is that the current solution is easy to use when using a barcode scanner.
In our use case we will scan a bunch of assets and hand them to the user.

**Comment by snipe** [comment]
That's an excellent reason :)

**Pull request merged**
