### PR TITLE
Fixes upload images problem with Docker installation.

### PR DESCRIPTION
**Pull request by mink-adao-duy**
Fixes the Docker installation where some folders were missing for uploading images.
The following folders will be created:
- data/uploads/categories
- data/uploads/companies
- data/uploads/departments
- data/uploads/locations
- data/uploads/manufacturers

### CODE REVIEW

**Comment by snipe** [comment]
Hi there - thanks for this! Can you please re-target this PR to point to the `develop` branch, per [our Contributing documentation](https://snipe-it.readme.io/docs/contributing-overview)? 

You don't need to close and re-open. After you create a pull request, you can modify the base branch so that the changes in the pull request are compared against a different branch. By changing the base branch of your original pull request rather than opening a new one with the correct base branch, you’ll be able to keep valuable work and discussion.

mhuxq

Thanks!

**Comment by mink-adao-duy** [comment]
Hi,
PR retargeted as recommended.
Sorry :/

**Comment by snipe** [comment]
Ack - can you rebase as well? Lots of my commits in there.

**Comment by mink-adao-duy** [comment]
Done

**Comment by snipe** [comment]
Hm, I'm still seeing hundreds of my own commits in this PR though. Did you do a fresh pull from develop?

**Comment by mink-adao-duy** [comment]
I'm so sorry but I don't really know how to do a fresh pull from develop from this PR :/
Do you think it would be easier to re-open a new PR from develop ?

**Comment by snipe** [comment]
It probably would be, yeah - not sure how far behind you are.

**Pull request closed without merging**
