### PR TITLE
Added EOS field (date type) in Asset Model

### PR DESCRIPTION
**Pull request by lea-mink**
Hello :)

For my usage, I have an EOL data which is a date and not a duration. So, I added EOL Support field (date type) in Asset Model.

I added a migration file, created with php artisan, I modified Model, Controller, Transformer, Presenter, Views & traduction files (en, fr) in adding EOL Support fied.

### CODE REVIEW

**Comment by snipe** [comment]
How would this work with the existing EOL? Can you provide screenshots?

**Comment by snipe** [comment]
(Also, please make sure to provide the english translations strings, otherwise the string itself will be dropped when we synchronize Crowdin)

**Comment by lea-mink** [comment]
Yes, I did the english translation, I just forgot to write it in the title of the commit.

The screenshots : 

Edit asset model 
editmodeleol

Models (all)
assetmodelvieweolsupport

Assets of a Model
modelassetseol

All Assets view
allasseteol

**Comment by lea-mink** [comment]
I developed this feature for my usage so I decided to share it if anyone wanted it.

The 2 fields are independents, so there is no conflict. So nothing happens when both are filled out and they are not the same. And nothing can make the users know which they should use.

What do you think about this feature ?

**Comment by lea-mink** [comment]
Your work is so amazing, I'm very satisfied by Snipe-IT. Everything is very usefull. 
However, when I'm using the EOL field, if the EOL is more than 1 year, I need to calculate the number of months, which a little bit tedious.
So I'm wondering, what was the objective of the field EOL support to be in months and not in date ?

**Comment by snipe** [comment]
Hi @lea-mink - EOL has traditionally been handled via months and not date, because many organizations have a policy of EOLing hardware after x months, so we calculate the EOL date based off of the EOL months and the purchase date. It just makes it easier for admins to figure out the EOL date automatically, instead of having to manually calculate the EOL date for every single item they add.

**Comment by snipe** [comment]
How about a compromise? If the EOL months have been entered and there is a purchase date, we could pre-populate the EOL date via javascript once they tab out of that field. If there are no EOL months given and/or no purchase date, accept the the date. We should probably also create a migration to check for EOL months and update the existing DB records to reflect that calculated date.

**Comment by cwoods131** [comment]
In our inventory we have many Chromebook devices which as shown here: https://support.google.com/chrome/a/answer/6220366?hl=en
They have exact dates where their support ends rather than months from the time of purchase. This is a great feature for these instances. Thank you

**Comment by lea-mink** [comment]
There is the freature request #1855 which talk about a EOS (End Of Support) field which is a date. It correspond to my modifications, so I renamed the field EOL Support by EOS.

**Comment by drumgod** [comment]
I really want this feature; how do i add this to my existing install? We are running v4.1.11-pre build 3288 (g426bf38)

**Comment by drumgod** [comment]
I figured out how to add this to my installation. How can i generate reports and use this new field? It does not show up as a field when i go to the custom reports page.

**Pull request closed without merging**
