### PR TITLE
Adding column for "Category" to view the asset's category when viewin…

### PR DESCRIPTION
**Pull request by seanmcilvenna**
Adding column for "Category" to view the asset's category when viewing a user's assigned assets

### CODE REVIEW

**Comment by snipe** [comment]
Hi there - thanks for this! Can you please re-target this PR to point to the `develop` branch, per [our Contributing documentation](https://snipe-it.readme.io/docs/contributing-overview)? 

You don't need to close and re-open. After you create a pull request, you can modify the base branch so that the changes in the pull request are compared against a different branch. By changing the base branch of your original pull request rather than opening a new one with the correct base branch, you’ll be able to keep valuable work and discussion.

mhuxq

Thanks!

**Comment by snipe** [comment]
Ack - can you rebase your develop branch? Seems we're a little bit ahead of you. (I'm seeing a ton of my own commits in this PR)

**Comment by snipe** [comment]
Your PR is small, so I can just apply your changes and add you as a contributor, but alternatively, you can read a little bit more about rebasing (why it matters and how to do it) [here](https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request). It's not actually hard or complicated, but it's up to you whether you want the Github "credit" for the PR :)

**Comment by seanmcilvenna** [comment]
Ok. I wouldn't mind the credit :)
But, I can't for the life of me figure out how to rebase onto YOUR develop branch.
So, I'm just gonna create a patch for my change, delete my fork, re-create it, and re-apply my patch in a new branch off of the "develop" branch. All that will probably take me less time :P

**Comment by snipe** [comment]
I totally understand :) Thanks so much for the contribution :)

**Pull request closed without merging**
