### PR TITLE
Make Model column a hyperlink to access the model page.

### PR DESCRIPTION
**Pull request by mtucker6784**
This will change the Model column on the Asset page to show a hyperlink that will allow a user to click the link and bring them to the model page in a new window.

Run on sentences ftmfw.

### CODE REVIEW

**Comment by snipe** [comment]
This looks great - my only comment is that we don't open links in a new window anywhere else in the app, so I'm not sure if that will be confusing/annoying for folks.

**Comment by mtucker6784** [comment]
Ahh, alrighty, no prob.

**Comment by snipe** [comment]
thumbs-up

**Comment by mtucker6784** [comment]
yay, it didn't blow up the demo site :P Haha.

**Pull request merged**
