### PR TITLE
Update upgrade.php

### PR DESCRIPTION
**Pull request by uknzaeinozpas**
posix_*() are not supported on Windows platform

### CODE REVIEW

**Comment by snipe** [comment]
Thanks! (Stupid windows. Grr.)

sv-money-unicorn

**Comment by snipe** [comment]
Actually, crap - that should have been targeted to develop. :-/

**Comment by uknzaeinozpas** [comment]
Yeah =D sorry, I always read that we should push to dev branch only and then I do it wrong myself -.-

**Comment by snipe** [comment]
No worries :) I pushed the patch to develop, so everything should be in sync

**Pull request merged**
