### PR TITLE
Improve German translations

### PR DESCRIPTION
**Pull request by xelan**
| Q             | A
| ------------- | ---
| Branch?       | develop
| Bug fix?      | yes
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | - (only translation strings changed)
| License       | GNU Affero General Public License v3.0

This PR changes some of the German translations to improve compatibility with the English ones. For example, "address" in English is (not) translated with "Supplier Address", which is apparently wrong.

Some missing translations are added, and some minor grammar mistakes and typos are fixed.

Certain phrases are adapted to achieve a more consistent nomenclature and style:

| old | new | reason |
| --- | --- | ---------------------------------------------------------- |
| Kennwort | Passwort | "Passwort" is more common and already used in most of the places within Snipe-IT |
| editieren | bearbeiten | "editieren" is hardly used in German, "bearbeiten" is the more common term, which is also used in most places of the Snipe-IT translations. |
| anschauen | ansehen | "anschauen" is more colloquial, most translation strings already used "ansehen" beforehand. |
| probieren | versuchen | "probieren" is more colloquial, most translation strings already used "versuchen" beforehand. The phrase "Versuchen Sie es erneut" (try again) is quite common in German-localized software. |

Previously, formal and informal forms of address were used inconsistently. Now, the formal salutation ("Sie") is used.

### CODE REVIEW

**Comment by xelan** [comment]
Travis failure on PHP 5.6 seems unrelated.

**Comment by snipe** [comment]
Hi @xelan - we use CrowdIn to handle translations. If there's something wrong, please update the language files through the CrowdIn interface. https://snipe-it.readme.io/docs/translations

**Comment by xelan** [comment]
Hi @snipe! Thanks for your fast response, I'll have a look at the CrowdIn platform.

**Comment by xelan** [comment]
Ok, I've suggested my changes via CrowdIn and voted where equivalent translations were already present.

**Pull request closed without merging**
