### PR TITLE
Fixed: #6306 - Seeding error

### PR DESCRIPTION
**Pull request by jwhulette**
Fixed seeder issue.

### CODE REVIEW

**Comment by snipe** [comment]
What does a seeded database with no settings record look like? Should we maybe just call the ResetDemo artisan command in the seeder so that a record exists?

All it does is this:


```
public function handle()
    {

        $this->info('Resetting the demo settings.');
        $settings = Setting::first();
        $settings->per_page = 20;
        $settings->site_name = 'Snipe-IT Asset Management Demo';
        $settings->auto_increment_assets = 1;
        $settings->logo = 'snipe-logo.png';
        $settings->alert_email = 'service@snipe-it.io';
        $settings->header_color = null;
        $settings->barcode_type = 'QRCODE';
        $settings->default_currency = 'USD';
        $settings->brand = 3;
        $settings->ldap_enabled = 0;
        $settings->full_multiple_companies_support = 1;
        $settings->alt_barcode = 'C128';
        $settings->skin = '';
        $settings->email_domain = 'snipeitapp.com';
        $settings->email_format = 'filastname';
        $settings->username_format = 'filastname';
        $settings->date_display_format = 'D M d, Y';
        $settings->time_display_format = 'g:iA';
        $settings->thumbnail_max_h = '30';
        $settings->locale = 'en';
        $settings->version_footer = 'on';
        $settings->support_footer = 'on';
        $settings->save();

        if ($user = User::where('username', '=', 'admin')->first()) {
            $user->locale = 'en';
            $user->save();
        }

        
    }
```

**Comment by snipe** [comment]
(Or we can create a settings seeder so we're not mixing artisan commands all over the place)

**Comment by snipe** [comment]
I'll do it :) I'm almost done anyway

**Comment by jwhulette** [comment]
@snipe don’t forget that the settings seeder has to run before the asset seeder.

**Comment by snipe** [comment]
I ran into an issue with this - wondering if they're being done in a transaction. I set the settings seeder first, but it still tripped on an asset-related seed due to a setting.

**Comment by jwhulette** [comment]
I’ll take a look. Is it in dev?

**Comment by snipe** [comment]
I think I got it now

**Pull request closed without merging**
