### PR TITLE
update broken link to contributor docs

### PR DESCRIPTION
**Pull request by imjennyli**

### CODE REVIEW

**Comment by snipe** [comment]
Hi @imjennyli - thanks for this! Per the contributing docs, can you please make this PR against develop?

**Comment by snipe** [comment]
Thanks! I also think you might need to rebase or do a fresh pull? I'm seeing all kinds of weird, older stuff in this PR.
screen shot 2017-10-03 at 9 50 11 am

**Comment by imjennyli** [comment]
@snipe yeah I'm seeing those too. I think git is smart and shouldn't include any of them in the pr merge (you can still see that only 1 file was changed), but I can just rebase tonight after I get home from work :)

**Comment by imjennyli** [comment]
@snipe cool, we should be good now! 😄

**Comment by snipe** [comment]
Sweet, thanks!

**Pull request merged**
